language: python

python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- '3.8'

sudo: false

env:
  PYTHONPATH: .:test
  PYTHONIOENCODING: utf-8

install:
- pip install -r requirements.txt

script:
- tox
- tox -e flake8
- pylint service.py resources/lib/ test/
- msgcmp resources/language/resource.language.{nl_nl,en_gb}/strings.po
#- kodi-addon-checker . --branch=krypton
#- kodi-addon-checker . --branch=leia
- coverage run -p -m unittest discover
- (sleep 10; pkill -ef -INT service.py || true) &
- coverage run -p --timid service.py
- sleep 2
#- coverage run -p test/run.py
#- pkill -ef -INT service.py || true

after_success:
- codecov
